### ISSUE TITLE
Build ROS 2 Java for Android fails: unexpected keyword argument 'post_process_callback'

### ISSUE THREAD

**Issue by NRottmann** [ros2-java/ros2_java#185]
Hi, I tried to build ROS 2 Java for Android but the build aborted with the following error:

```
Traceback (most recent call last):
  File "/home/nils/ros2_android_ws/src/ros2/rosidl/rosidl_generator_c/bin/rosidl_generator_c", line 40, in <module>
    sys.exit(main())
  File "/home/nils/ros2_android_ws/src/ros2/rosidl/rosidl_generator_c/bin/rosidl_generator_c", line 34, in main
    return generate_c(
  File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_generator_c/__init__.py", line 37, in generate_c
    return generate_files(
TypeError: generate_files() got an unexpected keyword argument 'post_process_callback'
make[2]: *** [CMakeFiles/rosidl_generator_c_interfaces__rosidl_generator_c.dir/build.make:110: rosidl_generator_c/rosidl_generator_c/msg/bool.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:168: CMakeFiles/rosidl_generator_c_interfaces__rosidl_generator_c.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< rosidl_generator_c [0.39s, exited with code 2]
Aborted  <<< rcutils [0.57s]

Summary: 66 packages finished [8.15s]
  1 package failed: rosidl_generator_c
  1 package aborted: rcutils
  1 package had stderr output: rosidl_generator_c
  24 packages not processed
```

Do you have any idea what went wrong?

**Comment by NRottmann** [comment]
Solved it. Obviously the problem was that the build does not work with ROS2 Foxy. Using ROS2 Dashing worked quite fine.
